hw1 done
Krock21rus/hwproj.me pull request #1
Opened 2019-01-19 12:10 UTC by Krock21rus

2019-01-19 19:21 UTC, yurii-litvinov requested changes

2019-01-19 19:21 UTC, yurii-litvinov commented on build.gradle
> +plugins {
Класть решение прямо в корень репозитория может быть нехорошо потому, что задач будет много, и их неплохо бы мерджить в мастер по мере сдачи.

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> + * HashTable
Не очень информативный комментарий

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    class StringList {
Со вложенными классами в Java не всё так просто. Он не static, поэтому ещё и хранит ссылку на объект объемлющего класса, и не может быть создан без объекта объемлющего класса, что, наверное, для списка не то, что хотелось. Кроме того, он не private, поэтому доступен из любого кода в этом же пакете. И вообще, мне кажется, что список вполне заслуживает быть классом верхнего уровня --- он же не деталь реализации хеш-таблицы, вне её бесполезная.

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        protected class StringListItem {
А protected в Java даёт ещё и пакетную видимость, так что это более широкая область видимости, чем надо. И опять-таки, надо его объявлять как static class

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +            StringListItem previous;
Модификаторы видимости вообще лучше всегда писать явно, потому что в разных языках разные умолчания и люди путаются. Вот тут, например, эти поля доступны для кода в том же пакете, так что это дыра в инкапсуляции и ужасно, хотя, наверное, имелось в виду, что они private

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +                next = previous = null;
Лучше одно присваивание за один раз. Такие конструкции несколько снижают читаемость программы.

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        private StringListItem head, tail;
Вот одно объявление переменной или поля на одной строчке совершенно точно надо. Объявление tail тут очень легко не заметить. Многословнее, но правильнее:
```java
private StringListItem head;
private StringListItem tail;
```

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +         * @return item
А зачем её возвращать, если мы её передали как параметр и она внутри не меняется?

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        String get(String key) {
Я б это сделал public, потому что это это ключевая для списка функциональность, и кто знает про список, должен уметь и делать get

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +                    head = tail = new StringListItem(key, value);
Тут тоже лучше по одному присваиванию за раз

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +                    StringListItem previoustail = tail;
camelCase, пожалуйста :)

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +         * @return String
Хм. Бесполезный комментарий, что это строка --- и так понятно. Но что за строка?

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        String getany() {
camelCase

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    HashTable() {
public? public-класс без public-способов создания его объектов может вызвать сильное разочарование у его пользователей :)

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        tableItemCount = 0;
Оно и так бы проинициализировалось нулём, Java-машина при создании объект заполняет нулями

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        return key.hashCode() % tableCapacity;
hashCode может возвращать отрицательные значения, % тоже, а код ниже к этому морально не готов. Так что оно **иногда** будет падать --- на длинных строках, некоторых строках национальных алфавитов и т.д.

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +     * @return item count in HashTable
Это тут можно вообще не писать, поскольку это дублирует общее описание.

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +     * @return String or null
Мне кажется, такие комментарии лучше не писать вовсе, и так из общего описания понятно

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    private void rebalance() {
Лучше не чередовать public и private

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashcode = getHashCode(key);
Если в качестве key передадут null, будет NullReferenceException, который указывает на то, что программист о чём-то не подумал. А я бы ожидал IllegalArgumentException, который указывает на то, что о чём-то не подумал пользователь

2019-01-19 19:21 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashcode = getHashCode(key);
camelCase?

2019-01-19 19:21 UTC, yurii-litvinov commented on src/test/java/me/hwproj/gaev/HashTableTest.java
> +        HashTable hashTable = new HashTable();
Имеет смысл использовать @BeforeEach для инициализации хеш-таблицы, а то копипаст

2019-01-19 21:22 UTC, Krock21 commented on build.gradle
> +plugins {
исправил

2019-01-19 21:23 UTC, Krock21 commented on src/main/java/me/hwproj/gaev/HashTable.java
> + * HashTable
убрал

2019-01-19 21:24 UTC, Krock21 commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    class StringList {
Вообще кажется что задание на Хеш таблицу, и пользователю будет странно получать ещё и List впридачу. Static не нужен, поскольку создаются объекты этого класса.

2019-01-19 21:24 UTC, Krock21 commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    class StringList {
Но я вынес его в другой файл и сделал package-private

2019-01-19 21:27 UTC, Krock21 commented on src/main/java/me/hwproj/gaev/HashTable.java
> +            StringListItem previous;
подразумеваются package-private модификаторы, поскольку необходим доступ к этим полям.
Технику getterов и setterов мы не проходили.

2019-01-19 21:28 UTC, Krock21 commented on src/main/java/me/hwproj/gaev/HashTable.java
> +     * @return String or null
Кажется из общего описания непонятно, что такое key. А в @param указывается. @return убрал

2019-01-19 21:29 UTC, Krock21 commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    private void rebalance() {
Переместил наверх

2019-01-19 21:30 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashcode = getHashCode(key);
То есть null.hashCode() возвращает NullReferenceException?
Тогда эта проблема почти везде, и я исправил её, добавив проверку в getHashCode

2019-01-19 21:30 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashcode = getHashCode(key);
Исправил

2019-01-19 21:31 UTC, Krock21rus commented on src/test/java/me/hwproj/gaev/HashTableTest.java
> +        HashTable hashTable = new HashTable();
Улучшил

2019-01-19 22:50 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +                next = previous = null;
Исправил

2019-01-19 22:51 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        private StringListItem head, tail;
Исправил

2019-01-19 22:51 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +         * @return item
Переделал на void

2019-01-19 22:51 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        String get(String key) {
Сделал, но кажется список не должен поставляться вместе с хештаблицей, поскольку пользователь хотел хештаблицу, а получил список

2019-01-19 22:52 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +                    head = tail = new StringListItem(key, value);
Исправил

2019-01-19 22:52 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +                    StringListItem previoustail = tail;
Исправил

2019-01-19 22:52 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        String getany() {
Исправил

2019-01-19 22:52 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    HashTable() {
Хмм, сделал конструкторы public

2019-01-19 22:53 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        tableItemCount = 0;
Лучше написать(для понятности), чем не написать и заставить разработчика думать

2019-01-19 22:53 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        return key.hashCode() % tableCapacity;
Исправил

2019-01-19 22:53 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +     * @return item count in HashTable
Убрал

2019-01-19 22:55 UTC, Krock21rus commented on src/main/java/me/hwproj/gaev/HashTable.java
> +         * @return String
Убрал

2019-01-20 10:07 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +    class StringList {
>Static не нужен, поскольку создаются объекты этого класса
Но я же писал, что в Java с вложенными классами не всё так просто :) static для вложенных классов означает, что класс не может использовать поля объемлющего класса. Это не мешает создавать объекты static-вложенного класса, иметь доступ к своим полям и т.д. Вот подробности: https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html, но вообще, Антон Михайлович потом целую лекцию вроде этому уделит.

2019-01-20 10:12 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +            StringListItem previous;
Ну её нечего и проходить, геттер --- это просто метод, возвращающий значение поля, а сеттер --- выставляет значение поля, ничего более. Никаких языковых механизмов для удобства этих дел в Java не предусмотрено. Доступ к полям из других классов --- в общем случае ошибка проектирования, хотя с учётом отсутствия в Java структур иногда может казаться альтернативой геттерам-сеттерам. Тем не менее, в Java-сообществе предпочитают именно геттеры-сеттеры, поэтому и я буду хотеть, чтобы поля всегда были только private.

2019-01-20 10:13 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        String get(String key) {
Аргумент. Но тогда я бы список сделал package-private, а все его методы public. Потому что если я решу передумать, мне достаточно будет только поменять видимость самого класса.

2019-01-20 10:16 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        tableItemCount = 0;
Согласен, хотя не делает так, кажется, вообще только C++. Так что инициализировать поля --- это такой способ показать своё C++-прошлое.  Зато если вы программируете одновременно и на Java, и на C++, привычка к инициализации может спасти жизнь. Поэтому ок, можно оставить.

2019-01-20 10:18 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +     * @return String or null
Ну загадочная фраза "String-key" мало что объясняет. Может, если бы было
```java
@param key a key which is used for value lookup in a hash table
```
было бы понятнее.

2019-01-20 10:20 UTC, yurii-litvinov commented on src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashcode = getHashCode(key);
`null.ЧтоУгодно()` --- это сразу креш. В Java любой метод по умолчанию виртуальный (а hashCode и по смыслу должен быть виртуальным, мы ж хотим его переопределять для своих типов), у null нет таблицы виртуальных методов, что делать рантайму, когда мы пытаемся вызвать метод?

2019-01-20 10:31 UTC, yurii-litvinov requested changes

2019-01-20 10:31 UTC, yurii-litvinov commented on hashtable/.gitignore
> +# From https://github.com/github/gitignore/blob/master/Gradle.gitignore
Не, gitignore лучше иметь один на весь репозиторий

2019-01-20 10:31 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +public class HashTable {
Вот то, что это отображение из строки в строку, можно было бы написать в комментарии. Может даже что оно работает за константное время.

2019-01-20 10:31 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +    private int tableItemCount, tableCapacity;
Тоже хотелось бы отдельно каждое объявление.

2019-01-20 10:31 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashCode = getHashCode(key);
Я бы тут ещё value запретил быть null, иначе как нам отличить отсутствие значения от значения, равного null? Ну или предложить какой-то другой способ работать с null-ами в качестве значений.

2019-01-20 10:31 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +            tableItemCount++;
Вот тут, например, если в value передали null, инвариант может нарушаться.

2019-01-27 20:02 UTC, Krock21rus commented on hashtable/.gitignore
> +# From https://github.com/github/gitignore/blob/master/Gradle.gitignore
Исправил

2019-01-27 20:03 UTC, Krock21rus commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +    private int tableItemCount, tableCapacity;
Исправил

2019-01-27 20:05 UTC, Krock21rus commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +        int hashCode = getHashCode(key);
просто запретил передавать null

2019-01-27 20:05 UTC, Krock21rus commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +            tableItemCount++;
Не можешь исправить - запрети)

2019-01-27 21:15 UTC, yurii-litvinov approved these changes
Замечания ещё остались, но они исправляются за полминуты, так что ладно, зачтена

2019-01-27 21:15 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/HashTable.java
> +        if(value == null) {
Надо пробел ещё

2019-01-27 21:15 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/StringList.java
> +        StringListItem previous;
Поля с пакетной видимостью, ужасно :)

2019-01-27 21:15 UTC, yurii-litvinov commented on hashtable/src/main/java/me/hwproj/gaev/StringList.java
> +    class StringListItem {
И вообще, эта штука по идее должна быть private

2019-01-27 21:55 UTC, merged